namespace Loupedeck.GoogleMeetPlugin
{
    using System;
    using System.Collections.Concurrent;

    internal static class Groups
    {
        public const String Call = "Call controls";
        public const String Panels = "Panels";
        public const String Reactions = "Reactions";
    }

    // Reactions in Meet's reaction bar. Keys match the extension's "react:<key>" commands
    // and the icon names in Icons/.
    internal static class Reactions
    {
        public static readonly (String Key, String Name)[] All =
        {
            ("heart", "Heart"),
            ("thumbsup", "Thumbs up"),
            ("party", "Celebrate"),
            ("clap", "Clap"),
            ("laugh", "Laugh"),
            ("surprised", "Surprised"),
            ("sad", "Sad"),
            ("thinking", "Thinking"),
            ("thumbsdown", "Thumbs down"),
        };
    }

    // Key images are SVGs embedded as "Icons.<key>.svg" (generated by tools/make-icons.mjs).
    internal static class Icons
    {
        private static readonly ConcurrentDictionary<String, BitmapImage> Cache = new();

        public static BitmapImage Get(Plugin plugin, String key) =>
            Cache.GetOrAdd(key, k => BitmapImage.FromResource(plugin.Assembly, $"Icons.{k}.svg"));
    }

    internal static class PluginExtensions
    {
        public static MeetBridge Bridge(this Plugin plugin) => ((GoogleMeetPlugin)plugin).Bridge;
    }
}
